<a href="https://colab.research.google.com/github/jsjj10002/Python_Basic/blob/main/ch10_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [ ]:
arr=[[0 for i in range(5)] for j in range(10)]
arr

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
size=5
numpyAry =np.random.randint(0,255,size=(size,size))
print(numpyAry)


[[ 82 224 117  84 250]
 [242   7 144 109 115]
 [174 117 166 215 219]
 [ 23 160  49 204 222]
 [ 28  57  83 239 118]]


In [ ]:
numpyAry+=100
print(numpyAry)

[[182 324 217 184 350]
 [342 107 244 209 215]
 [274 217 266 315 319]
 [123 260 149 304 322]
 [128 157 183 339 218]]


In [ ]:
pylist = [random.randint(0,225) for _ in range(5)]
print(pylist)


[215, 123, 210, 90, 129]


In [ ]:
numary1 = np.array(pylist)
print(numary1)

[215 123 210  90 129]


In [ ]:
numary2 = np.arange(5)
print(numary2)

[0 1 2 3 4]


In [ ]:
numary3 = np.arange(3,8)
print(numary3)

[3 4 5 6 7]


In [ ]:
numary4 = np.arange(0,100,20)
print(numary4)

[ 0 20 40 60 80]


In [ ]:
numary5 = np.ones(5)
print(numary5)

[1. 1. 1. 1. 1.]


In [ ]:
numary6 = np.zeros(5)
print(numary6)

[0. 0. 0. 0. 0.]


In [ ]:
numary7 = np.empty(6)
print(numary7)

[4.98582198e-310 0.00000000e+000 1.12426267e+166 5.98129759e-154
 5.04758700e+223 1.34452577e+161]


In [ ]:
numaary8 = np.full(5,33)
print(numaary8)

[33 33 33 33 33]


In [ ]:
numary9 = np.identity(5)
print(numary9)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
pylist1 = [10,20,30,40]
pylist2 = [10,20,30,40.0]
numary10 = np.array(pylist1)
print(numary10.dtype)
numary11 = np.array(pylist2)
print(numary11.dtype)
numary12 = np.array(pylist1, dtype=np.float32)
print(numary12,numary12.dtype)

int64
float64
[10. 20. 30. 40.] float32


In [ ]:
ary = np.random.randint(0,255,size=(2,3))
ary

array([[ 58,  13, 124],
       [224, 220,  53]])

In [ ]:
ary.ndim

2

In [ ]:
ary.shape

(2, 3)

In [ ]:
ary1 = np.arange(10)
ary1[0] =100
ary1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
ary1_sub1 = ary1[3:7]
ary1_sub1

array([3, 4, 5, 6])

In [ ]:
ary1_sub1[:] = 77
ary1_sub1

array([77, 77, 77, 77])

In [ ]:
ary1

array([100,   1,   2,  77,  77,  77,  77,   7,   8,   9])

In [ ]:
ary1 = np.arange(10)
ary1_sub2 =ary1[3:7].copy()
ary1_sub2

array([3, 4, 5, 6])

In [ ]:
ary1_sub2[:]=88
ary1_sub2

array([88, 88, 88, 88])

In [ ]:
ary1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ary2 = np.arange(1,26)
ary2 = ary2.reshape(5,5)
ary2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ary2 = np.arange(1,26).reshape(5,5)
ary2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ary3 = ary2.reshape(25)
ary3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [2]:
ary4 = np.arange(16).reshape(4,4)
ary4[1]

array([4, 5, 6, 7])

In [5]:
ary4_sub =ary4[:,1:2]
print(ary4_sub)
ary4_sub.shape

[[ 1]
 [ 5]
 [ 9]
 [13]]


(4, 1)

In [6]:
ary4[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [9]:
ary5 = np.zeros((2,2),dtype=np.int8)
print(ary5)
ary6 =np.ones((2,2), dtype=np.int8)
print(ary6)
print(np.concatenate((ary5,ary6), axis=0))
print(np.concatenate((ary5,ary6), axis=1))

[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[0 0]
 [0 0]
 [1 1]
 [1 1]]
[[0 0 1 1]
 [0 0 1 1]]


In [10]:
ary7 = np.array([[1,2,3],[4,5,6]])
print(ary7.T,"\n")
print(ary7.transpose(1,0),"\n")
print(ary7.transpose(0,1),"\n")


[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]] 

[[1 2 3]
 [4 5 6]] 

